#! /bin/sh

# Autostart
# xrandr -s 1920x1080 &
pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/launch.sh &
nitrogen --restore &

bspc monitor -d I II III IV V VI

bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

#bspc config focused_border_color "#ff6666"
#bspc config normal_border_color "#ff6666"

xsetroot -cursor_name left_ptr &

picom
glava --desktop
xscreensaver -no-splash
